version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_SECONDARY_MODEL: ${OPENAI_SECONDARY_MODEL}
      CRAWLER_HEADLESS: ${CRAWLER_HEADLESS}
      MAX_REQUEST_RETRIES: ${MAX_REQUEST_RETRIES}
      REQUEST_HANDLER_TIMEOUT: ${REQUEST_HANDLER_TIMEOUT}
      STORAGE_DIR: ${STORAGE_DIR}
      CRAWLER_BASE_URL: ${CRAWLER_BASE_URL}
      CRAWLER_TOKEN: ${CRAWLER_TOKEN}
      SERVER_PORT: ${SERVER_PORT}
    volumes:
      - .:/app
    # command: ["node", "dist/main"]